### ISSUE TITLE
editorda alert va shunga o'xshash narsalarni ishlatilgan paytda xatolik chiqardi. Xatolik pastdagi rasmda to'liq ko'rsatilgan shuni hal qilish kerak.

### ISSUE THREAD

**Issue by shakhbozbekusmonov** [udemere/udemere-editor#1]
<img width="1460" alt="Screenshot 2024-08-26 at 6 45 50 PM" src="https://github.com/user-attachments/assets/af2394a3-8d88-4b55-b699-813aaed661e6">

**Comment by EshimovShaxzod** [comment]
Assalomu aleykum. Muammo tushunarli. hal qilamiz

**Comment by EshimovShaxzod** [comment]
Alert va shu kabi funksiyalarni ishlamasligini sababi code editorimiz client tomonda emas balki server tomonda ishlayotgani ekan. Nodejs alert, propmt kabi funksiyalarni tanimayapti. Unga brauzer muxiti kerak ekan. Shu qismi ozroq o'ylantiryapti
